I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: DynamicImage 'gui/button/gallerybutton[prefix_]_idle.png': could not find image. ('gui/button/gallerybuttoninsensitive__idle.png', 'gui/button/gallerybutton_idle.png', and 1 more.)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/core.py", line 2218, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/core.py", line 2748, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 1 more time]
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/screen.py", line 485, in visit_all
    self.child.visit_all(callback, seen=None)
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 8 more times]
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/displayable.py", line 424, in visit_all
    for d in self.visit():
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/image.py", line 785, in visit
    self.find_target()
  File "/Users/mfaiq/Downloads/renpy-8.3.7-sdk/renpy/display/image.py", line 683, in find_target
    raise Exception(error)
Exception: DynamicImage 'gui/button/gallerybutton[prefix_]_idle.png': could not find image. ('gui/button/gallerybuttoninsensitive__idle.png', 'gui/button/gallerybutton_idle.png', and 1 more.)

macOS-15.5-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
Game Jam 1.0
Sun Jun  8 13:14:05 2025
